// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ToDoCalendarWeb.Controllers;

#nullable disable

namespace ToDoCalendarWeb.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240321121330_InitWithSeed")]
    partial class InitWithSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ToDoCalendarWeb.Domain.Diff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ChangeTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ObjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PropName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Diffs");
                });

            modelBuilder.Entity("ToDoCalendarWeb.Domain.Period", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RoutineId")
                        .HasColumnType("uuid");

                    b.Property<string>("TimePeriod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoutineId");

                    b.ToTable("Periods");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6ebcaabe-6bb4-4412-94c6-1cd6c9480721"),
                            DayOfWeek = 0,
                            Name = "Уборка",
                            RoutineId = new Guid("1f8c6ba0-b06f-4979-a84a-0c789d5ae168"),
                            TimePeriod = "{\"StartTime\":\"10:00:00\",\"EndTime\":\"12:00:00\"}"
                        },
                        new
                        {
                            Id = new Guid("7adee775-c6d8-4d6a-924e-316232303a69"),
                            DayOfWeek = 0,
                            Name = "Завтрак",
                            RoutineId = new Guid("1e642aac-2cc5-4a70-bfa3-903ca4349f14"),
                            TimePeriod = "{\"StartTime\":\"08:00:00\",\"EndTime\":\"10:00:00\"}"
                        },
                        new
                        {
                            Id = new Guid("1f351d75-1e0e-4163-9bce-06a9e7e123cc"),
                            DayOfWeek = 0,
                            Name = "Обед",
                            RoutineId = new Guid("1e642aac-2cc5-4a70-bfa3-903ca4349f14"),
                            TimePeriod = "{\"StartTime\":\"12:00:00\",\"EndTime\":\"14:00:00\"}"
                        },
                        new
                        {
                            Id = new Guid("236f1c19-ffa9-4d84-975a-8a32e8ee6df7"),
                            DayOfWeek = 0,
                            Name = "Ужин",
                            RoutineId = new Guid("1e642aac-2cc5-4a70-bfa3-903ca4349f14"),
                            TimePeriod = "{\"StartTime\":\"18:00:00\",\"EndTime\":\"20:00:00\"}"
                        },
                        new
                        {
                            Id = new Guid("5a58b463-ed8c-429e-905a-1fac51176435"),
                            DayOfWeek = 0,
                            Name = "Работа",
                            RoutineId = new Guid("b41acb52-dd15-4567-a09d-17db0cc28998"),
                            TimePeriod = "{\"StartTime\":\"14:00:00\",\"EndTime\":\"18:00:00\"}"
                        });
                });

            modelBuilder.Entity("ToDoCalendarWeb.Domain.Routine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Routines");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1f8c6ba0-b06f-4979-a84a-0c789d5ae168"),
                            Name = "Уборка"
                        },
                        new
                        {
                            Id = new Guid("1e642aac-2cc5-4a70-bfa3-903ca4349f14"),
                            Name = "Готовка"
                        },
                        new
                        {
                            Id = new Guid("b41acb52-dd15-4567-a09d-17db0cc28998"),
                            Name = "Работа"
                        });
                });

            modelBuilder.Entity("ToDoCalendarWeb.Domain.Task", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTracked")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PeriodId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PeriodId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("656f7f70-6bcf-42b3-92df-b1e6390578e5"),
                            Description = "",
                            IsCompleted = false,
                            IsDraft = false,
                            IsTracked = true,
                            Name = "Убрать пыль",
                            PeriodId = new Guid("6ebcaabe-6bb4-4412-94c6-1cd6c9480721")
                        },
                        new
                        {
                            Id = new Guid("cc15dd8f-d486-47bb-97eb-c0ca02972220"),
                            Description = "",
                            IsCompleted = false,
                            IsDraft = false,
                            IsTracked = true,
                            Name = "Помыть окно",
                            PeriodId = new Guid("6ebcaabe-6bb4-4412-94c6-1cd6c9480721")
                        },
                        new
                        {
                            Id = new Guid("4ed80e97-bf91-46cd-a689-cb705b859755"),
                            Description = "",
                            IsCompleted = false,
                            IsDraft = false,
                            IsTracked = true,
                            Name = "Доделать пэт проект",
                            PeriodId = new Guid("5a58b463-ed8c-429e-905a-1fac51176435")
                        },
                        new
                        {
                            Id = new Guid("61c82b03-9a8d-4e53-b053-c7477b218e6a"),
                            Description = "",
                            IsCompleted = false,
                            IsDraft = false,
                            IsTracked = true,
                            Name = "Прочитать главу книги",
                            PeriodId = new Guid("5a58b463-ed8c-429e-905a-1fac51176435")
                        });
                });

            modelBuilder.Entity("ToDoCalendarWeb.Domain.Period", b =>
                {
                    b.HasOne("ToDoCalendarWeb.Domain.Routine", null)
                        .WithMany("Periods")
                        .HasForeignKey("RoutineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ToDoCalendarWeb.Domain.Task", b =>
                {
                    b.HasOne("ToDoCalendarWeb.Domain.Period", null)
                        .WithMany("Tasks")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ToDoCalendarWeb.Domain.Period", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("ToDoCalendarWeb.Domain.Routine", b =>
                {
                    b.Navigation("Periods");
                });
#pragma warning restore 612, 618
        }
    }
}
